### ISSUE TITLE
I am getting error while unpack this msapp file. 

### ISSUE THREAD

**Issue by TheSimbani** [microsoft/PowerApps-Tooling#499]
Unpack: C:\Release\AsiaRequestforKeepingDeadStock.msapp --> C:\Release\AsiaRequestforKeepingDeadStock
Warning PA2001: Checksum mismatch. File Controls\12.json checksum does not match on extract
Warning PA2001: Checksum mismatch. File Controls\276.json checksum does not match on extract
Warning PA2001: Checksum mismatch. File Controls\333.json checksum does not match on extract
Warning PA2001: Checksum mismatch. File Controls\361.json checksum does not match on extract
Warning PA2001: Checksum mismatch. File Controls\415.json checksum does not match on extract
Warning PA2001: Checksum mismatch. File Header.json checksum does not match on extract
Error   PA3011: Roundtrip validation on unpack failed. 

**To Reproduce**

1. Unpacking 

**Additional context**

**Comment by petrochuk** [comment]
Do you have simple msapp file we can use to repro or can you provide steps to create one?

**Comment by marcelbf** [comment]
please, let us know if you're still facing issue.
can you repro with a sample .msapp that you can share?
