### ISSUE TITLE
Error messages appears when using pac solution sync

### ISSUE THREAD

**Issue by MuhammadQaiserKS** [microsoft/PowerApps-Tooling#500]
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.

Error occurred using PAC CLI.

**To Reproduce**
[PAC CLI Error.md](https://github.com/microsoft/PowerApps-Language-Tooling/files/13501886/PAC.CLI.Error.md)

**Comment by marcelbf** [comment]
please, let us know if you're still facing issue.
can you repro with a sample .msapp that you can share?
