### ISSUE TITLE
Error   PA3013: Property Value Changed: TopParent.Index

### ISSUE THREAD

**Issue by jberu622Neudesic** [microsoft/PowerApps-Tooling#502]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

Starting: pac - Clone or Sync Solution
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.232.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\3-5297-4360-9aeb-81745b3c0485.ps1'"
'***' authenticated successfully.
Validating connection...
Default organization: Dev
Connected to... Dev
Connected as ***
Authentication profile created
    * DATAVERSE ppdev                          https:// XXXXX.crm.dynamics.com/    : ***     Public

Cloned solution available; Triggering Solution Sync
Pointing to cdsproj folder path -  D:\a\1\s\field-client-source\slnFieldClient\SolutionPackage
Triggering Sync - solution sync --processCanvasApps true --packagetype Both --async
Connected to... Dev
Connected as ***

Starting Solution Export...

 - SystemUser
Processing Component: Workflows
 - Field Client Initial Ticket Synch
 - xxxSync to Field Client
 - FieldClient Sync to xxxx
 - Field Client Wipe Tables
Processing Component: EntityRelationships
Processing Component: MobileOfflineProfiles
 - FieldClientOfflineProfile
Processing Component: CanvasApps
 - fc_fieldclientgallerycomponentlibrary_10cf9
 - fc_fieldclient_8d8f4
 - fc_fieldclientcomponents_530f1

-- unpacking Canvas app fc_fieldclientgallerycomponentlibrary_10cf9...
Unpack from D:\a\1\s\field-client-source\slnFieldClient\SolutionPackage\src\CanvasApps\fc_fieldclientgallerycomponentlibrary_10cf9_DocumentUri.msapp --> D:\a\1\s\field-client-source\slnFieldClient\SolutionPackage\src\CanvasApps\src\fc_fieldclientgallerycomponentlibrary_10cf9
  source format version: 0.24

-- unpacking Canvas app fc_fieldclient_8d8f4...
Unpack from D:\a\1\s\field-client-source\slnFieldClient\SolutionPackage\src\CanvasApps\fc_fieldclient_8d8f4_DocumentUri.msapp --> D:\a\1\s\field-client-source\slnFieldClient\SolutionPackage\src\CanvasApps\src\fc_fieldclient_8d8f4
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.29.11+g9e2b163
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3013: Property Value Changed: TopParent.Index
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

**To Reproduce**

1. Unpacking the application 

**Screenshots**

<img width="742" alt="image" src="https://github.com/microsoft/PowerApps-Language-Tooling/assets/59027173/58ae493a-291c-429f-a75d-7d665eabd297">

**Additional context**

This started happening this week after attempting to deploy an update to the application. We are using the ALM accelerator application.

**Comment by BetimBeja** [comment]
You have this in you logs before the error:
```
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
```

Maybe some merge issues? does this error manifest with pac cli? what about older versions of pac cli?
