### ISSUE TITLE
Trying to run the build.cmd and I receive an error

### ISSUE THREAD

**Issue by jwolmanSymplr** [microsoft/PowerApps-Tooling#582]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**
Trying to run the build.cmd and I receive an error

C:\PowerApps-Tooling\PowerApps-Tooling-master>build.cmd
fatal: not a git repository (or any of the parent directories): .git
Unable to find root directory using git, assuming this script is being run from root = C:\PowerApps-Tooling\PowerApps-Tooling-master
rebuild: Starting... (rebuild)
rebuild: clean: Starting...
targets: dotnet clean "C:\PowerApps-Tooling\PowerApps-Tooling-master\src\PASopa.sln" --configuration Debug /clp:verbosity=minimal /flp:Verbosity=normal;LogFile="C:\PowerApps-Tooling\PowerApps-Tooling-master\obj\logs\clean-Debug.log" /flp3:PerformanceSummary;Verbosity=diag;LogFile="C:\PowerApps-Tooling\PowerApps-Tooling-master\obj\logs\clean-Debug.diagnostics.log"  /nologo
MSBUILD : error MSB1009: Project file does not exist.
Switch: C:\PowerApps-Tooling\PowerApps-Tooling-master\src\PASopa.sln
rebuild: clean: Failed! The command exited with code 1. (363 ms)
rebuild: ───────────────────────────────
rebuild: Target  Outcome  Duration
rebuild: ──────  ───────  ──────────────
rebuild: clean   Failed!  363 ms  100.0%
rebuild: ───────────────────────────────
rebuild: Failed! (rebuild) (369 ms)

Please mention if it is reproduced using PAC CLI or PASopa. *(Please mention the version number, if possible)*

**To Reproduce**

1. Unpacking or packing 

**Screenshots**

If applicable, add screenshots of error messages to help explain your problem.

**Additional context**

Add any helpful context on the .msapp like created from teams, contains custom pcf components, etc.

**Comment by petrochuk** [comment]
You can go to 'src' folder and run `dotnet build`
