### ISSUE TITLE
ALM error: Error PA3013: Property Value Changed: UsedTemplates[0].Name

### ISSUE THREAD

**Issue by MarenBru** [microsoft/PowerApps-Tooling#667]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing.
<img width="658" alt="errorDO" src="https://github.com/microsoft/PowerApps-Tooling/assets/158040363/3752daf3-34e7-4689-89aa-590b2d1536df">

**Describe the bug**

I have the same issue with two different solutions. We are not able to find the error and need your help.

This error occours under "pac - Clone or Sync Solution":

Error PA3013: Property Value Changed: UsedTemplates[0].Name
Error PA3013: Property Value Changed: UsedTemplates[0].Template
Error PA3013: Property Value Changed: UsedTemplates[0].Version
Error PA3013: Property Value Changed: UsedTemplates[1].Name
Error PA3013: Property Value Changed: UsedTemplates[1].Template
Error PA3013: Property Value Changed: UsedTemplates[1].Version
Error PA3013: Property Value Changed: UsedTemplates[2].Name
Error PA3013: Property Value Changed: UsedTemplates[2].Template
Error PA3013: Property Value Changed: UsedTemplates[2].Version
Error PA3013: Property Value Changed: UsedTemplates[3].Name
Error PA3013: Property Value Changed: UsedTemplates[3].Template
Error PA3013: Property Value Changed: UsedTemplates[3].Version
Error PA3013: Property Value Changed: UsedTemplates[4].Name
Error PA3013: Property Value Changed: UsedTemplates[4].Template
Error PA3013: Property Value Changed: UsedTemplates[4].Version
Error PA3013: Property Value Changed: UsedTemplates[5].Name
Error PA3013: Property Value Changed: UsedTemplates[5].Template

.... and more all the way down to number 10.

This is the end message: Error PA3011: Roundtrip validation on unpack failed.

Used ALM Accelerator and this error is in DevOps.

**Additional context**

Using this version of the ALM Accelerator: 1.0.20240305.1

**Comment by lasjoe** [comment]
I have the same issue since today

**Comment by Coding-Chem-Kitten** [comment]
We have the same issue since yesterday.

**Comment by pkm90** [comment]
Same issue

**Comment by petrochuk** [comment]
Do you have --processCanvasApps flag? Can you try removing it?

**Comment by pkm90** [comment]
> Do you have --processCanvasApps flag? Can you try removing it?

I'm having the issue when unpacking solutions locally.
Removing the flag does remove the error, but it means that I can't store changes of canvas apps in version control.

Has there been a change from PowerApps side in terms of how canvas components are stored?

**Comment by rfarris2000** [comment]
FYI - Rolling back the editor version to 3.24052.30 worked for us and allowed us to run the unpack command.  

This error is different but is similar to this one #668.  We were told they aren't going to fix it.

**Comment by Coding-Chem-Kitten** [comment]
Do you mean running a previous ALM version? Ours is an ALM issue.

**Comment by rfarris2000** [comment]
No mean rolling back the Editor version in the canvas app:

![image](https://github.com/microsoft/PowerApps-Tooling/assets/1624416/11e30cae-e65d-44d7-81f0-c6296fa3b537)

**Comment by MarenBru** [comment]
We did try to remove a modern table component from the solution, which seemed to be solving the issue. However, one of the solutions is entirely dependent on that component, so we cannot remove it there. Is there another workaround?

**Comment by MarenBru** [comment]
> Do you have --processCanvasApps flag? Can you try removing it?

Do you have an explanation or a link on how to do this?

**Comment by tamilst2** [comment]
Same issue with pac canvas unpack with latest power apps version release. Combo box Microsoft_CoreControls_ComboBoxTemplate_dataField causing the issue (previous package pcfDataField_1.4.0). Once enabled to this new control, unable to revert back to older power apps version since it only show last 3 power apps authoring versions. So please provide a fix asap since unable to unpack canvas app (aware of this not to be used for production use but still a prob for development use).

**Comment by lasjoe** [comment]
As advised here:
https://powerusers.microsoft.com/t5/Building-Power-Apps/Commit-to-GIT-error-since-today/td-p/2792452/page/2?lightbox-message-images-2794045=878423iAC3D0E6057F4B968

Adding `&studio-version=v3.24052.30.298708436` to the end of app edit URL and saving the app temporarily fixes the issue.

**Comment by Masciuniria** [comment]
Thank you very much @lasjoe for sharing that. It worked!

**Comment by Coding-Chem-Kitten** [comment]
Thank you for sharing that @lasjoe  it worked for us too!

**Comment by marcelbf** [comment]
it is same issue as [668](https://github.com/microsoft/PowerApps-Tooling/issues/668)
