### ISSUE TITLE
Cannot unpack canvas app with Modern Controls Combobox & Dropdown 

### ISSUE THREAD

**Issue by rontan09** [microsoft/PowerApps-Tooling#668]
- [ ] Please attach a sample .msapp to this Issue which demonstrates the issue you are experiencing. *(Please do not attach any file which may contain sensitive personal or company data.)*

**Describe the bug**

Not able to unpack msapp file with Modern Control with the latest version of powerapps "3.24054.19".
It was previously working fine until last week.

I created a test app for troubleshooting and found out issue also appearing.

**To Reproduce**

1. Unpacking 
pac canvas unpack --msapp ModernControlv2.msapp --sources ./ModernControlv2

pac canvas unpack --msapp ModernControlv2.msapp --sources ./ModernControlv2
Warning: canvas unpack is in preview, and functionality is not guaranteed. Use extreme caution if using in a production environment. For more information see https://aka.ms/paccanvas
Unpack from C:\src\papps\ModernControlv2.msapp --> C:\src\papps\ModernControlv2
Microsoft PowerPlatform CLI
Version: 1.32.8+gf89d946
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Error   PA3999: Unable to parse template file PowerApps_CoreControls_DropdownCanvasTemplate_dataField

**Comment by rontan09** [comment]
[ModernControlv2.zip](https://github.com/user-attachments/files/15760323/ModernControlv2.zip)

Sample App with Modern Control ( Combobox with Field) & Dropdown with Field)

![image](https://github.com/microsoft/PowerApps-Tooling/assets/43241512/161a23b5-3448-4d11-b40d-00c57d037aa1)

**Comment by rfarris2000** [comment]
Line 62 in ControlParserTemplate.cs is throwing a duplicate key exemption.  

Method is TryParseTemplate.

**Comment by petrochuk** [comment]
As announced during Microsoft Build conference the direction is to eliminate the need for this pack/unpack tool

**Comment by rfarris2000** [comment]
What kind of answer is that?  That's great that is planned to eliminate but this is a big right now that is preventing us from committing to source control.

**Comment by petrochuk** [comment]
> What kind of answer is that? That's great that is planned to eliminate but this is a bug right now that is preventing us from committing to source control.

Thank you for providing your feedback. We will work on making it clearer that PaSopa has always been an experimental tool and is not recommended for production use. We have included multiple warnings in the documentation to indicate this:

https://github.com/microsoft/PowerApps-Tooling/tree/master/src/PASopa
https://github.com/microsoft/PowerApps-Tooling/blob/master/docs/YAMLFileFormat.md

**Comment by petrochuk** [comment]
> What kind of answer is that? That's great that is planned to eliminate but this is a bug right now that is preventing us from committing to source control.

FYI: This project is open-sourced, and we welcome contributions from the community. If you have a proposed fix, please feel free to open a pull request and we will be happy to review it.

**Comment by marcelbf** [comment]
Workaround at the moment is to save the .msapp in a previous version 

you can add `&studio-version=v3.24052.30.298708436` to the URL within PowerApps Studio as listed [here](https://powerusers.microsoft.com/t5/Building-Power-Apps/Commit-to-GIT-error-since-today/td-p/2792452/page/2?lightbox-message-images-2794045=878423iAC3D0E6057F4B968)

**Comment by petrochuk** [comment]
@pkm90 

Good overview: [Enable every developer to collaborate with low code + pro code | BRK202](https://www.youtube.com/watch?v=jH0QE9bQz5U&ab_channel=MicrosoftDeveloper)

There are also [Community Office Hours that are open to the public to join (third (3rd) Thursday of the month between 11:00am - 12:00pm US Pacific Time - Excluding holidays)](https://github.com/microsoft/powerplatform-build-tools/blob/main/community/Office_Hours.md) where you can talk and provide feedback to some team members directly.

I hope this helps.

**Comment by rrrahate** [comment]
> Workaround at the moment is to save the .msapp in a previous version
> 
> you can add `&studio-version=v3.24052.30.298708436` to the URL within PowerApps Studio as listed [here](https://powerusers.microsoft.com/t5/Building-Power-Apps/Commit-to-GIT-error-since-today/td-p/2792452/page/2?lightbox-message-images-2794045=878423iAC3D0E6057F4B968)

I added the working studio version but still no success.

**Comment by marcelbf** [comment]
> I added the working studio version but still no success.

are you sure it is the same issue? Can you easily repro with a sample .msapp that you can send?

This [PR](https://github.com/microsoft/PowerApps-Tooling/pull/670) fixed this specific issue - had confirmation from more than one user that it works, and we are planning to release to PAC CLI very soon.

**Comment by rfarris2000** [comment]
> > I added the working studio version but still no success.
> 
> are you sure it is the same issue? Can you easily repro with a sample .msapp that you can send?
> 
> This [PR](https://github.com/microsoft/PowerApps-Tooling/pull/670) fixed this specific issue - had confirmation from more than one user that it works, and we are planning to release to PAC CLI very soon.

Any update on the PAC CLI fix?

**Comment by rrrahate** [comment]
What is the tentative release date for PAC CLI update to fix this issue? @marcelbf

**Comment by LukasSchauffele** [comment]
Hi Team - do you have any updates on when this bugfix will be released?

**Comment by marcelbf** [comment]
PAC CLI is now released with this fix - https://www.nuget.org/packages/Microsoft.PowerApps.CLI#releasenotes-body-tab
