### ISSUE TITLE
Issue in Commit using ALM Accelerator to GIthub (pac- clone or sync step)

### ISSUE THREAD

**Issue by nikhildubey-abi** [microsoft/PowerApps-Tooling#673]
Facing error in committing power platform solution using ALM Accelerator, even if we try with new solution.

The error is in Pac-clone or sync solution.

![image](https://github.com/microsoft/PowerApps-Tooling/assets/173244288/8bee37b1-2f41-4db2-b56c-da76929bb280)

**Comment by eruturaj** [comment]
Same error for me as well from past 2 days for one particular solution 
![Github_error](https://github.com/microsoft/PowerApps-Tooling/assets/55569752/e97331d1-bc98-451d-bdb1-b1cc494d002b)

**Comment by marcelbf** [comment]
are you using modern controls? I believe it is the same issue as reported [here](https://github.com/microsoft/PowerApps-Tooling/issues/668)
