### ISSUE TITLE
Error PA3013: Property Value Changed: UsedTemplates[0].Name

### ISSUE THREAD

**Issue by skfd** [microsoft/PowerApps-Tooling#695]
**Describe the bug**

`pac solution sync --processCanvasApps --packagetype both` extracts some changes and then fails for specific canvas app.

I'm sorry I can not attach the app. Please let me know if there is a verbose logging I can turn on or something like that...

**To Reproduce**

Can not repro in the fresh app.

**Additional context**

```
Warning PA2001: Checksum mismatch. Checksum doesn't match on extract.
Warning PA2001: Checksum mismatch. File Properties.json checksum does not match on extract
  source format version: 0.24
Warning PA2001: Checksum mismatch. Checksum indicates that sources have been edited since they were unpacked. If this was intentional, ignore this warning.
Microsoft PowerPlatform CLI
Version: 1.32.8+gf89d946
Online documentation: https://aka.ms/PowerPlatformCLI
Feedback, Suggestions, Issues: https://github.com/microsoft/powerplatform-build-tools/discussions

Error: Error   PA3013: Property Value Changed: UsedTemplates[0].Name
Error   PA3013: Property Value Changed: UsedTemplates[0].Template
Error   PA3013: Property Value Changed: UsedTemplates[0].Version
Error   PA3013: Property Value Changed: UsedTemplates[1].Name
Error   PA3013: Property Value Changed: UsedTemplates[1].Template
Error   PA3013: Property Value Changed: UsedTemplates[1].Version
Error   PA3013: Property Value Changed: UsedTemplates[2].Name
Error   PA3013: Property Value Changed: UsedTemplates[2].Template
Error   PA3013: Property Value Changed: UsedTemplates[2].Version
Error   PA3013: Property Value Changed: UsedTemplates[3].Name
Error   PA3013: Property Value Changed: UsedTemplates[3].Template
Error   PA3013: Property Value Changed: UsedTemplates[3].Version
Error   PA3013: Property Value Changed: UsedTemplates[4].Name
Error   PA3013: Property Value Changed: UsedTemplates[4].Template
Error   PA3013: Property Value Changed: UsedTemplates[4].Version
Error   PA3013: Property Value Changed: UsedTemplates[5].Name
Error   PA3013: Property Value Changed: UsedTemplates[5].Template
Error   PA3013: Property Value Changed: UsedTemplates[5].Version
Error   PA3011: Roundtrip validation on unpack failed.
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling

```

**Comment by JakeStratton** [comment]
we are having the exact same error.  happened a few weeks ago, worked yesterday, started again today:

Error   PA3013: Property Value Changed: UsedTemplates[0].Name
Error   PA3013: Property Value Changed: UsedTemplates[0].Template
Error   PA3013: Property Value Changed: UsedTemplates[0].Version
Error   PA3013: Property Value Changed: UsedTemplates[1].Name
Error   PA3013: Property Value Changed: UsedTemplates[1].Template
Error   PA3013: Property Value Changed: UsedTemplates[1].Version
Error   PA3013: Property Value Changed: UsedTemplates[2].Name
Error   PA3013: Property Value Changed: UsedTemplates[2].Template
Error   PA3013: Property Value Changed: UsedTemplates[2].Version
Error   PA3013: Property Value Changed: UsedTemplates[3].Name
Error   PA3013: Property Value Changed: UsedTemplates[3].Template
Error   PA3013: Property Value Changed: UsedTemplates[3].Version
Error   PA3011: Roundtrip validation on unpack failed. 
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling
