### ISSUE TITLE
oom on msapps with large files

### ISSUE THREAD

**Issue by MikeStall** [microsoft/PowerApps-Tooling#94]
The basic problem is that we load the entire msapp into memory (CanvasDocument). 

And then oom at places like this:

```
                        case FileKind.AppCheckerResult:
                            var appChecker = Encoding.UTF8.GetString(entry.ToBytes());
                            app._entropy.AppCheckerResult = appChecker;
                            break;
```

We should calculating this in a streaming way rather than ToBytes(). 
(sarif file can be huge)

We should scrutinize usage of FileEntry.ToBytes, and probably need to be lazier and have documents backed by disk.

**Comment by landonarogers** [comment]
@MikeStall Is this issue still in progress?
